# Generated by Django 5.2.5 on 2025-08-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="링크"),
        ),
        migrations.AlterField(
            model_name="post",
            name="region",
            field=models.CharField(
                choices=[
                    ("Europe", "유럽"),
                    ("Asia", "아시아"),
                    ("Oceania", "오세아니아"),
                    ("America", "아메리카"),
                ],
                default="Asia",
                max_length=20,
                verbose_name="지역",
            ),
        ),
    ]
