-- [V] Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
	START WITH 1 -- 1부터 시작(기본값)
	INCREMENT BY 1 -- 1씩 증가(기본값)
	MAXVALUE 9999 -- 최대값
	MINVALUE 1   -- 최소값
	NOCYCLE -- CYCLE : 순차번호 9999->1
	NOCACHE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 다음 순차번호 값
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 다음 순차번호 값

DROP TABLE FRIEND;
CREATE TABLE FRIEND(
	NO NUMBER(5) PRIMARY KEY,
	NAME VARCHAR2(30) NOT NULL,
	TEL VARCHAR2(20)	UNIQUE,
	ADDRESS VARCHAR2(250),
	LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
	MAXVALUE 99999
	NOCACHE NOCYCLE;
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
	VALUES(FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999','서울');
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
	VALUES(FRIEND_SEQ.NEXTVAL, '유길동', NULL,'서울');
SELECT * FROM FRIEND;

--------------
-- !! 연습문제 --
--------------
DROP TABLE MEMBER;
DROP SEQUENCE MEMBER_SQ;

CREATE TABLE MEMBER_LEVEL (
    LEVELNO   NUMBER PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL
);

CREATE TABLE MEMBER (
    mNO      NUMBER PRIMARY KEY,
    mNAME    VARCHAR2(20) NOT NULL,
    mPW      VARCHAR2(8) NOT NULL,
    mEMAIL   VARCHAR2(100) UNIQUE,
    mPOINT   NUMBER CHECK (mPOINT >= 0),
    mRDATE   DATE DEFAULT SYSDATE,
    LEVELNO  NUMBER,
    FOREIGN KEY (LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)
);

SELECT * FROM MEMBER_LEVEL;
SELECT * FROM MEMBER;


CREATE SEQUENCE MEMBER_SQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

INSERT INTO MEMBER_LEVEL VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드');

INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, mRDATE, LEVELNO)
	VALUES (MEMBER_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, TO_DATE('2024/09/26', 'YYYY-MM-DD'), 0
);

INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, mRDATE, LEVELNO)
	VALUES (MEMBER_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, TO_DATE('2022/04/01', 'YYYY-MM-DD'), 1
);

----- !! 출력 !! -----

SELECT
	M.mNO,
	M.mNAME,
	TO_CHAR(M.mRDATE, 'YYYY-MM-DD') AS mRDATE,
	M.mEMAIL AS mMAIL,
	M.mPOINT AS point,
	ML.LEVELNAME
FROM
	MEMBER M,
	MEMBER_LEVEL ML
WHERE
	M.LEVELNO = ML.LEVELNO
ORDER BY
	M.mNO;












