# Generated by Django 5.2.5 on 2025-08-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=50, verbose_name="책이름"),
        ),
    ]
